name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push docker image 
      run: |
           echo  "${{ secrets.docker }}"  | docker login -n "skillassure" --password-stdin
           docker build -t skillassure:github-1 .
           docker push skillassure:github-1
